"use strict";
var FEED_RETRIEVAL_METHOD;
(function (FEED_RETRIEVAL_METHOD) {
    FEED_RETRIEVAL_METHOD[FEED_RETRIEVAL_METHOD["FETCHED_AUTOMATICALLY"] = 'FETCHED_AUTOMATICALLY'] = "FETCHED_AUTOMATICALLY";
    FEED_RETRIEVAL_METHOD[FEED_RETRIEVAL_METHOD["PRODUCED_IN_HOUSE"] = 'PRODUCED_IN_HOUSE'] = "PRODUCED_IN_HOUSE";
    FEED_RETRIEVAL_METHOD[FEED_RETRIEVAL_METHOD["MANUALLY_UPLOADED"] = 'MANUALLY_UPLOADED'] = "MANUALLY_UPLOADED";
})(FEED_RETRIEVAL_METHOD = exports.FEED_RETRIEVAL_METHOD || (exports.FEED_RETRIEVAL_METHOD = {}));
